// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyJTiL9JMq2yTCHkhCwcG207Br_Sw_n04',
    appId: '1:839430557537:web:d278a36551d5884e347f20',
    messagingSenderId: '839430557537',
    projectId: 'kel1-8ae2e',
    authDomain: 'kel1-8ae2e.firebaseapp.com',
    databaseURL: 'https://kel1-8ae2e-default-rtdb.firebaseio.com',
    storageBucket: 'kel1-8ae2e.appspot.com',
    measurementId: 'G-NNK0WSK9R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7iHNTMs2RjzGpgTIsTJmjKzrUXehQ0Mw',
    appId: '1:839430557537:android:97d0a4142deb2ca0347f20',
    messagingSenderId: '839430557537',
    projectId: 'kel1-8ae2e',
    databaseURL: 'https://kel1-8ae2e-default-rtdb.firebaseio.com',
    storageBucket: 'kel1-8ae2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqr6cG8u4uT2uMa7Q6xMbfXePl0Abe1n0',
    appId: '1:839430557537:ios:90f295bc038d5c11347f20',
    messagingSenderId: '839430557537',
    projectId: 'kel1-8ae2e',
    databaseURL: 'https://kel1-8ae2e-default-rtdb.firebaseio.com',
    storageBucket: 'kel1-8ae2e.appspot.com',
    iosBundleId: 'com.example.tesflut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqr6cG8u4uT2uMa7Q6xMbfXePl0Abe1n0',
    appId: '1:839430557537:ios:913dafe9d193f279347f20',
    messagingSenderId: '839430557537',
    projectId: 'kel1-8ae2e',
    databaseURL: 'https://kel1-8ae2e-default-rtdb.firebaseio.com',
    storageBucket: 'kel1-8ae2e.appspot.com',
    iosBundleId: 'com.example.tesflut.RunnerTests',
  );
}
